package bo.com.offercruz.entidades;
// Generated 18-nov-2014 1:51:54 by Hibernate Tools 3.6.0



/**
 * Imagencontenido generated by hbm2java
 */
public class Imagencontenido  implements java.io.Serializable {


     private Integer id;
     private Imagen imagen;
     private Contenido contenido;

    public Imagencontenido() {
    }

    public Imagencontenido(Imagen imagen, Contenido contenido) {
       this.imagen = imagen;
       this.contenido = contenido;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Imagen getImagen() {
        return this.imagen;
    }
    
    public void setImagen(Imagen imagen) {
        this.imagen = imagen;
    }
    public Contenido getContenido() {
        return this.contenido;
    }
    
    public void setContenido(Contenido contenido) {
        this.contenido = contenido;
    }




}


